name: Validate Password

on:
  workflow_dispatch: # This will allow manual testing
  repository_dispatch:
    types: [validate-password]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check Password
        run: |
          echo "${{ secrets.AUDIT_LOG_VIEWER_PASSWORD }}" > password.txt
          PASSWORD=$(cat password.txt)
          if [ "$PASSWORD" == "${{ github.event.client_payload.password }}" ]; then
            echo "::set-output name=validation::success"
          else
            echo "::set-output name=validation::failure"
          fi
        id: validate

      - name: Return Response
        run: |
          echo "${{ steps.validate.outputs.validation }}"
